# config.yaml
# This is an example provided by Rishi.
# 1. Create different configuration files and schemas for different operation
# e.g. data loading, preprocessing, training, evaluating
# 2. Keep configurations in /conf/ subdirectories associated with their operation
# 3. For any config.yaml files, you will need an associated schema.py file for parsing them

# observing pg. 16 of https://arxiv.org/pdf/2004.10964.pdf

model_name: roberta-base
train_dataset: imdb
run_id: '1'
bsz: 16
seed: 1
dropout_probability: 0.1
adam_beta_1: 0.9
adam_beta_2: 0.999
max_epochs: 4
dataset_size: full
patience: 3
learning_rate: 0.00002
num_train_epochs: 10
per_device_train_batch_size: 8
num_labels: 2
save_steps: 2500