name: mjolnir
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- absl-py=0.12.0
- aiohttp=3.7.4
- appnope=0.1.2
- argon2-cffi=20.1.0
- async-timeout=3.0.1
- async_generator=1.10
- attrs=20.3.0
- backcall=0.2.0
- blas=1.0
- bleach=3.3.0
- blinker=1.4
- brotlipy=0.7.0
- bzip2=1.0.8
- c-ares=1.17.1
- ca-certificates=2020.12.5
- cachetools=4.2.1
- certifi=2020.12.5
- cffi=1.14.5
- chardet=4.0.0
- click=7.1.2
- coverage=5.5
- cryptography=3.4.6
- cython=0.29.17
- dbus=1.13.18
- decorator=4.4.2
- defusedxml=0.7.1
- entrypoints=0.3
- expat=2.2.10
- ffmpeg=4.3
- freetype=2.10.4
- fsspec=0.8.7
- future=0.18.2
- gettext=0.19.8.1
- glib=2.67.4
- gmp=6.2.1
- gnutls=3.6.5
- google-auth=1.24.0
- google-auth-oauthlib=0.4.1
- grpcio=1.36.1
- icu=58.2
- idna=2.10
- importlib-metadata=2.0.0
- importlib_metadata=2.0.0
- intel-openmp=2019.4
- ipykernel=5.3.4
- ipython=7.21.0
- ipython_genutils=0.2.0
- ipywidgets=7.6.3
- jedi=0.17.0
- jinja2=2.11.3
- jpeg=9b
- jsonschema=3.2.0
- jupyter=1.0.0
- jupyter_client=6.1.7
- jupyter_console=6.2.0
- jupyter_core=4.7.1
- jupyterlab_pygments=0.1.2
- jupyterlab_widgets=1.0.0
- lame=3.100
- lcms2=2.11
- libcxx=10.0.0
- libedit=3.1.20191231
- libffi=3.3
- libiconv=1.16
- libpng=1.6.37
- libprotobuf=3.14.0
- libsodium=1.0.18
- libtiff=4.1.0
- libuv=1.40.0
- lz4-c=1.9.3
- markdown=3.3.4
- markupsafe=1.1.1
- mistune=0.8.4
- mkl=2019.4
- mkl-service=2.3.0
- mkl_fft=1.3.0
- mkl_random=1.1.1
- multidict=5.1.0
- nbclient=0.5.3
- nbconvert=6.0.7
- nbformat=5.1.2
- ncurses=6.2
- nest-asyncio=1.5.1
- nettle=3.4.1
- ninja=1.10.2
- notebook=6.2.0
- numpy=1.19.2
- numpy-base=1.19.2
- oauthlib=3.0.1
- olefile=0.46
- openh264=2.1.0
- openssl=1.1.1j
- packaging=20.9
- pandoc=2.11
- pandocfilters=1.4.3
- parso=0.8.1
- pcre=8.44
- pexpect=4.8.0
- pickleshare=0.7.5
- pillow=8.1.2
- pip=21.0.1
- prometheus_client=0.9.0
- prompt-toolkit=3.0.8
- prompt_toolkit=3.0.8
- protobuf=3.14.0
- ptyprocess=0.7.0
- pyasn1=0.4.8
- pyasn1-modules=0.2.7
- pycparser=2.20
- pygments=2.8.1
- pyjwt=2.0.1
- pyopenssl=20.0.1
- pyparsing=2.4.7
- pyqt=5.9.2
- pyrsistent=0.17.3
- pysocks=1.7.1
- python=3.8.8
- python-dateutil=2.8.1
- python_abi=3.8
- pytorch=1.8.0
- pytorch-lightning=1.2.3
- pyyaml=5.4.1
- pyzmq=20.0.0
- qt=5.9.7
- qtconsole=5.0.2
- qtpy=1.9.0
- readline=8.1
- requests=2.25.1
- requests-oauthlib=1.3.0
- rsa=4.7.2
- send2trash=1.5.0
- setuptools=52.0.0
- sip=4.19.8
- six=1.15.0
- sqlite=3.33.0
- tensorboard=2.4.1
- tensorboard-plugin-wit=1.8.0
- terminado=0.9.2
- testpath=0.4.4
- tk=8.6.10
- torchaudio=0.8.0
- torchvision=0.9.0
- tornado=6.1
- tqdm=4.59.0
- traitlets=5.0.5
- typing-extensions=3.7.4.3
- typing_extensions=3.7.4.3
- urllib3=1.26.3
- wcwidth=0.2.5
- webencodings=0.5.1
- werkzeug=1.0.1
- wheel=0.36.2
- widgetsnbextension=3.5.1
- xz=5.2.5
- yaml=0.2.5
- yarl=1.6.3
- zeromq=4.3.3
- zipp=3.4.0
- zlib=1.2.11
- zstd=1.4.5
- pip:
  - appdirs==1.4.4
  - black==20.8b1
  - cfgv==3.2.0
  - configparser==5.0.2
  - cycler==0.10.0
  - distlib==0.3.1
  - docker-pycreds==0.4.0
  - filelock==3.0.12
  - flake8==3.8.4
  - gitdb==4.0.5
  - gitpython==3.1.14
  - identify==2.1.1
  - isort==5.7.0
  - kiwisolver==1.3.1
  - matplotlib==3.3.4
  - mccabe==0.6.1
  - mypy-extensions==0.4.3
  - nodeenv==1.5.0
  - pathspec==0.8.1
  - pathtools==0.1.2
  - pre-commit==2.11.1
  - promise==2.3
  - psutil==5.8.0
  - pycodestyle==2.6.0
  - pyflakes==2.2.0
  - regex==2020.11.13
  - sentry-sdk==1.0.0
  - shortuuid==1.0.1
  - smmap==3.0.5
  - subprocess32==3.5.4
  - toml==0.10.2
  - typed-ast==1.4.2
  - virtualenv==20.4.2
  - wandb==0.10.22
